name: Scheduled fetch

on:
  schedule:
    # 毎事55分に実行 (UTC)
    - cron: '57 * * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: fetch
        run: deno run -A fetchNewsAll.js
      - name: commit and push
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add .
          git commit -m 'deno fmt' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
          git push
